name: Auto Login to Lunes Dashboard

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 1:00 执行一次

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run login script
        run: node login.js
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}

      # 🚫 不使用 upload-artifact，避免报错
